/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <jvmti.h>

/* Header for class com_barchart_udt_CCC */

#ifndef _Included_com_barchart_udt_CCC
#define _Included_com_barchart_udt_CCC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_barchart_udt_CCC
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_barchart_udt_CCC_initNative
  (JNIEnv *, jobject);

/*
 * Class:     com_barchart_udt_CCC
 * Method:    setACKTimer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_barchart_udt_CCC_setACKTimer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_barchart_udt_CCC
 * Method:    setACKInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_barchart_udt_CCC_setACKInterval
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_barchart_udt_CCC
 * Method:    setRTO
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_barchart_udt_CCC_setRTO
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_barchart_udt_CCC
 * Method:    setPacketSndPeriod
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_barchart_udt_CCC_setPacketSndPeriod
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_barchart_udt_CCC
 * Method:    setCWndSize
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_barchart_udt_CCC_setCWndSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_barchart_udt_CCC
 * Method:    getPerfInfo
 * Signature: ()Lcom/barchart/udt/MonitorUDT;
 */
JNIEXPORT jobject JNICALL Java_com_barchart_udt_CCC_getPerfInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif